title: VIVA LA VIDA
permalink: '/:title.html'
url: https://bybl.ga # the base hostname & protocol for your site, e.g. http://example.com

author: Taumini # add your name
about-author: 我的个性很机车，我的手段很阴险。

paginate: 6
paginate_path: /page:num/

markdown: kramdown

plugins:
  - jekyll-paginate
